// <auto-generated />
using Cos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cos.Migrations
{
    [DbContext(typeof(CDBContext))]
    [Migration("20190712012955_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Cos.Models.Mails.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Infos");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("SubmitDate");

                    b.HasKey("Id");

                    b.ToTable("Me");
                });

            modelBuilder.Entity("Cos.Models.RichAndArticles.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArticleContext");

                    b.Property<string>("ArticleCreateDate");

                    b.Property<string>("ArticleImgUrl");

                    b.Property<string>("ArticleName");

                    b.Property<string>("ArticleSideName");

                    b.Property<string>("ArticleUpdateDate");

                    b.Property<string>("UserName");

                    b.Property<string>("type");

                    b.HasKey("Id");

                    b.ToTable("Ar");
                });

            modelBuilder.Entity("Cos.Models.RichAndArticles.SimpleArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArticleContext");

                    b.Property<string>("ArticleCreateDate");

                    b.Property<string>("ArticleImgUrl");

                    b.Property<string>("ArticleUpdateDate");

                    b.Property<string>("UserName");

                    b.Property<string>("type");

                    b.HasKey("Id");

                    b.ToTable("Si");
                });

            modelBuilder.Entity("Cos.Models.ScrollPictures.ScrollPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImgSubmitDate");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("PicName");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Sc");
                });
#pragma warning restore 612, 618
        }
    }
}
